language: python
python:
  - '3.6'
before_install:
  - sudo apt-get update -qq
install: pip install sphinx sphinx-gallery sphinx-rtd-theme numpydoc wget pysptools cvxopt numpy h5py matplotlib wget pyUSID
script: pwd
after_success:
  - sphinx-build -b html -aET docs docs/_build/html
  - touch docs/_build/html/.nojekyll
deploy:
# Github pages deployment
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUBTOKEN
    local_dir: docs/_build/html