name: build

env:
  PYTHON_MAIN_VERSION: 3.8
  
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    tags:
        - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install basics
      run: |
        sudo apt-get update -qq
        python -m pip install --upgrade pip

    - name: Documentation build
      if: ${{github.ref == 'refs/heads/master'}}
      run: |
        pip install sphinx>=3.1.1 sphinx-gallery sphinx-rtd-theme>=0.5.0 sphinx-autodoc-typehints numpydoc wget nbsphinx numpy h5py matplotlib sidpy pyUSID
        sudo apt-get install pandoc
        sphinx-build -b html -aET docs/source docs/_build/html
        touch docs/_build/html/.nojekyll
        
    - name: Deploy to GitHub Pages
      if: ${{github.ref == 'refs/heads/master'}}
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/_build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
